version: '3'
services:
  frontend:
    build: .
    image: myyarnproject2
    container_name: frontend2
    restart: always
    working_dir: /usr/src
    ports:
      - 3000
    volumes: 
      - .:/usr/src
    #networks:
    #  mynetwork:
    #    ipv4_address: 192.168.2.99
    stdin_open: true
    #environment:
    #  - HOST=192.168.2.99

#networks:
#  mynetwork:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.2.100/29
#          gateway: 192.168.2.97